CURDIR=$(shell pwd)
PACKAGE_VERSION :=
PACKAGE_DIR :=
PACKAGE_CONF :=
first_rule: all

all: build

build:
	$(MAKE) -C $(CURDIR)/PACKAGE/libuuid      first_rule

config_rule:

install_rule install:

clean_rule distclean clean:
	rm OBJ/ TARGET/ -rf

uninstall_rule uninstall:

